
const config = {
    ACLOCAL_PATH: "C:\Program Files\Git\mingw64\share\aclocal;C:\Program Files\Git\usr\share\aclocal",
    ALLUSERSPROFILE: "C:\ProgramData",
    APPDATA: "C:\Users\jesus\AppData\Roaming",
    CHROME_CRASHPAD_PIPE_NAME: "\\.\pipe\crashpad_10604_XSXPJDKPYKCSMVBF",
    COLOR: "1",
    COLORTERM: "truecolor",
    COMMONPROGRAMFILES: "C:\Program Files\Common Files",
    CommonProgramFiles(x86): "C:\Program Files (x86)\Common Files",
    CommonProgramW6432: "C:\Program Files\Common Files",
    COMPUTERNAME: "LAPTOP-2OURGFEJ",
    COMSPEC: "C:\WINDOWS\system32\cmd.exe",
    CONFIG_SITE: "C:/Program Files/Git/etc/config.site",
    DISPLAY: "needs-to-be-defined",
    DriverData: "C:\Windows\System32\Drivers\DriverData",
    EDITOR: "C:\WINDOWS\notepad.exe",
    EXEPATH: "C:\Program Files\Git\bin",
    GIT_ASKPASS: "c:\Users\jesus\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh",
    HOME: "C:\Users\jesus",
    HOMEDRIVE: "C:",
    HOMEPATH: "\Users\jesus",
    HOST: "http://localhost/DELATEL/",
    HOSTNAME: "LAPTOP-2OURGFEJ",
    INFOPATH: "C:\Program Files\Git\mingw64\local\info;C:\Program Files\Git\mingw64\share\info;C:\Program Files\Git\usr\local\info;C:\Program Files\Git\usr\share\info;C:\Program Files\Git\usr\info;C:\Program Files\Git\share\info",
    INIT_CWD: "C:\xampp\htdocs\Delatel",
    LANG: "es_ES.UTF-8",
    LOCALAPPDATA: "C:\Users\jesus\AppData\Local",
    LOGONSERVER: "\\LAPTOP-2OURGFEJ",
    MANPATH: "C:\Program Files\Git\mingw64\local\man;C:\Program Files\Git\mingw64\share\man;C:\Program Files\Git\usr\local\man;C:\Program Files\Git\usr\share\man;C:\Program Files\Git\usr\man;C:\Program Files\Git\share\man",
    MINGW_CHOST: "x86_64-w64-mingw32",
    MINGW_PACKAGE_PREFIX: "mingw-w64-x86_64",
    MINGW_PREFIX: "C:/Program Files/Git/mingw64",
    MSYS: "disable_pcon",
    MSYSTEM: "MINGW64",
    MSYSTEM_CARCH: "x86_64",
    MSYSTEM_CHOST: "x86_64-w64-mingw32",
    MSYSTEM_PREFIX: "C:/Program Files/Git/mingw64",
    NODE: "C:\Program Files\nodejs\node.exe",
    npm_command: "run-script",
    npm_config_cache: "C:\Users\jesus\AppData\Local\npm-cache",
    npm_config_globalconfig: "C:\Users\jesus\AppData\Roaming\npm\etc\npmrc",
    npm_config_global_prefix: "C:\Users\jesus\AppData\Roaming\npm",
    npm_config_init_module: "C:\Users\jesus\.npm-init.js",
    npm_config_local_prefix: "C:\xampp\htdocs\Delatel",
    npm_config_node_gyp: "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js",
    npm_config_noproxy: "",
    npm_config_npm_version: "10.2.4",
    npm_config_prefix: "C:\Users\jesus\AppData\Roaming\npm",
    npm_config_userconfig: "C:\Users\jesus\.npmrc",
    npm_config_user_agent: "npm/10.2.4 node/v20.11.1 win32 x64 workspaces/false",
    npm_execpath: "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js",
    npm_lifecycle_event: "generate-config",
    npm_lifecycle_script: "node generate-config.js",
    npm_node_execpath: "C:\Program Files\nodejs\node.exe",
    npm_package_json: "C:\xampp\htdocs\Delatel\package.json",
    NUMBER_OF_PROCESSORS: "8",
    OneDrive: "C:\Users\jesus\OneDrive",
    OneDriveConsumer: "C:\Users\jesus\OneDrive",
    OPENRDA_INI: "C:\Program Files (x86)\CA\ERwin Data Modeler r7.3\OpenAccess\bin\iwinnt\openrda.ini",
    ORIGINAL_PATH: "C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\jesus\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn;C:\Program Files\Azure Data Studio\bin;C:\Program Files\nodejs;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Users\jesus\AppData\Local\Programs\Python\Launcher;C:\Users\jesus\AppData\Local\Microsoft\WindowsApps;C:\Users\jesus\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\jesus\.dotnet\tools;C:\Program Files\Azure Data Studio\bin;C:\Users\jesus\AppData\Roaming\npm;C:\Users\jesus\AppData\Roaming\Composer\vendor\bin;C:\Users\jesus\AppData\Local\spicetify",
    ORIGINAL_TEMP: "C:/Users/jesus/AppData/Local/Temp",
    ORIGINAL_TMP: "C:/Users/jesus/AppData/Local/Temp",
    ORIGINAL_XDG_CURRENT_DESKTOP: "undefined",
    OS: "Windows_NT",
    PATH: "C:\xampp\htdocs\Delatel\node_modules\.bin;C:\xampp\htdocs\node_modules\.bin;C:\xampp\node_modules\.bin;C:\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\lib\node-gyp-bin;C:\Users\jesus\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\jesus\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn;C:\Program Files\Azure Data Studio\bin;C:\Program Files\nodejs;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Users\jesus\AppData\Local\Programs\Python\Launcher;C:\Users\jesus\AppData\Local\Microsoft\WindowsApps;C:\Users\jesus\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\jesus\.dotnet\tools;C:\Program Files\Azure Data Studio\bin;C:\Users\jesus\AppData\Roaming\npm;C:\Users\jesus\AppData\Roaming\Composer\vendor\bin;C:\Users\jesus\AppData\Local\spicetify;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl",
    PATHEXT: ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC",
    PKG_CONFIG_PATH: "C:\Program Files\Git\mingw64\lib\pkgconfig;C:\Program Files\Git\mingw64\share\pkgconfig",
    PKG_CONFIG_SYSTEM_INCLUDE_PATH: "C:/Program Files/Git/mingw64/include",
    PKG_CONFIG_SYSTEM_LIBRARY_PATH: "C:/Program Files/Git/mingw64/lib",
    PLINK_PROTOCOL: "ssh",
    PROCESSOR_ARCHITECTURE: "AMD64",
    PROCESSOR_IDENTIFIER: "Intel64 Family 6 Model 140 Stepping 1, GenuineIntel",
    PROCESSOR_LEVEL: "6",
    PROCESSOR_REVISION: "8c01",
    ProgramData: "C:\ProgramData",
    PROGRAMFILES: "C:\Program Files",
    ProgramFiles(x86): "C:\Program Files (x86)",
    ProgramW6432: "C:\Program Files",
    PROMPT: "$P$G",
    PSModulePath: "C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules",
    PUBLIC: "C:\Users\Public",
    PWD: "C:/xampp/htdocs/Delatel",
    SESSIONNAME: "Console",
    SHELL: "C:\Program Files\Git\usr\bin\bash.exe",
    SHLVL: "2",
    SSH_ASKPASS: "C:/Program Files/Git/mingw64/bin/git-askpass.exe",
    SYSTEMDRIVE: "C:",
    SYSTEMROOT: "C:\WINDOWS",
    TEMP: "C:\Users\jesus\AppData\Local\Temp",
    TERM: "xterm-256color",
    TERM_PROGRAM: "vscode",
    TERM_PROGRAM_VERSION: "1.92.1",
    TMP: "C:\Users\jesus\AppData\Local\Temp",
    TMPDIR: "C:\Users\jesus\AppData\Local\Temp",
    USERDOMAIN: "LAPTOP-2OURGFEJ",
    USERDOMAIN_ROAMINGPROFILE: "LAPTOP-2OURGFEJ",
    USERNAME: "jesus",
    USERPROFILE: "C:\Users\jesus",
    VSCODE_GIT_ASKPASS_EXTRA_ARGS: "",
    VSCODE_GIT_ASKPASS_MAIN: "c:\Users\jesus\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js",
    VSCODE_GIT_ASKPASS_NODE: "C:\Users\jesus\AppData\Local\Programs\Microsoft VS Code\Code.exe",
    VSCODE_GIT_IPC_HANDLE: "\\.\pipe\vscode-git-db5f9561ae-sock",
    WINDIR: "C:\WINDOWS",
    ZES_ENABLE_SYSMAN: "1",
    _: "C:/Program Files/nodejs/node.exe"
};

export default config;
